/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUserManagementRouteImport } from './routes/_authenticated/user-management'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWebsitesIndexRouteImport } from './routes/_authenticated/websites/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSpidersIndexRouteImport } from './routes/_authenticated/spiders/index'
import { Route as AuthenticatedSpiderSessionsIndexRouteImport } from './routes/_authenticated/spider-sessions/index'
import { Route as AuthenticatedSpiderPackagesIndexRouteImport } from './routes/_authenticated/spider-packages/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services/index'
import { Route as AuthenticatedServersIndexRouteImport } from './routes/_authenticated/servers/index'
import { Route as AuthenticatedReqsIndexRouteImport } from './routes/_authenticated/reqs/index'
import { Route as AuthenticatedPrejobsIndexRouteImport } from './routes/_authenticated/prejobs/index'
import { Route as AuthenticatedPreTasksIndexRouteImport } from './routes/_authenticated/pre-tasks/index'
import { Route as AuthenticatedLinksIndexRouteImport } from './routes/_authenticated/links/index'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs/index'
import { Route as AuthenticatedJobgroupsIndexRouteImport } from './routes/_authenticated/jobgroups/index'
import { Route as AuthenticatedIndustriesIndexRouteImport } from './routes/_authenticated/industries/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedEntrypointsIndexRouteImport } from './routes/_authenticated/entrypoints/index'
import { Route as AuthenticatedClustersIndexRouteImport } from './routes/_authenticated/clusters/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedBlackwordsIndexRouteImport } from './routes/_authenticated/blackwords/index'
import { Route as AuthenticatedArticlesIndexRouteImport } from './routes/_authenticated/articles/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedActorsIndexRouteImport } from './routes/_authenticated/actors/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedMaterialVideoRouteImport } from './routes/_authenticated/material/video'
import { Route as AuthenticatedMaterialUnknownRouteImport } from './routes/_authenticated/material/unknown'
import { Route as AuthenticatedMaterialTradeRouteImport } from './routes/_authenticated/material/trade'
import { Route as AuthenticatedMaterialSubsRouteImport } from './routes/_authenticated/material/subs'
import { Route as AuthenticatedMaterialSpeechRouteImport } from './routes/_authenticated/material/speech'
import { Route as AuthenticatedMaterialShopRouteImport } from './routes/_authenticated/material/shop'
import { Route as AuthenticatedMaterialRecruitRouteImport } from './routes/_authenticated/material/recruit'
import { Route as AuthenticatedMaterialProductRouteImport } from './routes/_authenticated/material/product'
import { Route as AuthenticatedMaterialNoteRouteImport } from './routes/_authenticated/material/note'
import { Route as AuthenticatedMaterialNewsRouteImport } from './routes/_authenticated/material/news'
import { Route as AuthenticatedMaterialImageRouteImport } from './routes/_authenticated/material/image'
import { Route as AuthenticatedMaterialFileRouteImport } from './routes/_authenticated/material/file'
import { Route as AuthenticatedMaterialCustomizeRouteImport } from './routes/_authenticated/material/customize'
import { Route as AuthenticatedMaterialCompanyRouteImport } from './routes/_authenticated/material/company'
import { Route as AuthenticatedMaterialBookRouteImport } from './routes/_authenticated/material/book'
import { Route as AuthenticatedMaterialBidRouteImport } from './routes/_authenticated/material/bid'
import { Route as AuthenticatedMaterialAudioRouteImport } from './routes/_authenticated/material/audio'
import { Route as AuthenticatedMaterialArticleRouteImport } from './routes/_authenticated/material/article'
import { Route as AuthenticatedMaterialAccountRouteImport } from './routes/_authenticated/material/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserManagementRoute =
  AuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebsitesIndexRoute =
  AuthenticatedWebsitesIndexRouteImport.update({
    id: '/websites/',
    path: '/websites/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpidersIndexRoute =
  AuthenticatedSpidersIndexRouteImport.update({
    id: '/spiders/',
    path: '/spiders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpiderSessionsIndexRoute =
  AuthenticatedSpiderSessionsIndexRouteImport.update({
    id: '/spider-sessions/',
    path: '/spider-sessions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpiderPackagesIndexRoute =
  AuthenticatedSpiderPackagesIndexRouteImport.update({
    id: '/spider-packages/',
    path: '/spider-packages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServersIndexRoute =
  AuthenticatedServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReqsIndexRoute = AuthenticatedReqsIndexRouteImport.update({
  id: '/reqs/',
  path: '/reqs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrejobsIndexRoute =
  AuthenticatedPrejobsIndexRouteImport.update({
    id: '/prejobs/',
    path: '/prejobs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPreTasksIndexRoute =
  AuthenticatedPreTasksIndexRouteImport.update({
    id: '/pre-tasks/',
    path: '/pre-tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLinksIndexRoute = AuthenticatedLinksIndexRouteImport.update({
  id: '/links/',
  path: '/links/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobgroupsIndexRoute =
  AuthenticatedJobgroupsIndexRouteImport.update({
    id: '/jobgroups/',
    path: '/jobgroups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustriesIndexRoute =
  AuthenticatedIndustriesIndexRouteImport.update({
    id: '/industries/',
    path: '/industries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrypointsIndexRoute =
  AuthenticatedEntrypointsIndexRouteImport.update({
    id: '/entrypoints/',
    path: '/entrypoints/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClustersIndexRoute =
  AuthenticatedClustersIndexRouteImport.update({
    id: '/clusters/',
    path: '/clusters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlackwordsIndexRoute =
  AuthenticatedBlackwordsIndexRouteImport.update({
    id: '/blackwords/',
    path: '/blackwords/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArticlesIndexRoute =
  AuthenticatedArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActorsIndexRoute =
  AuthenticatedActorsIndexRouteImport.update({
    id: '/actors/',
    path: '/actors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedMaterialVideoRoute =
  AuthenticatedMaterialVideoRouteImport.update({
    id: '/material/video',
    path: '/material/video',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialUnknownRoute =
  AuthenticatedMaterialUnknownRouteImport.update({
    id: '/material/unknown',
    path: '/material/unknown',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialTradeRoute =
  AuthenticatedMaterialTradeRouteImport.update({
    id: '/material/trade',
    path: '/material/trade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialSubsRoute =
  AuthenticatedMaterialSubsRouteImport.update({
    id: '/material/subs',
    path: '/material/subs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialSpeechRoute =
  AuthenticatedMaterialSpeechRouteImport.update({
    id: '/material/speech',
    path: '/material/speech',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialShopRoute =
  AuthenticatedMaterialShopRouteImport.update({
    id: '/material/shop',
    path: '/material/shop',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialRecruitRoute =
  AuthenticatedMaterialRecruitRouteImport.update({
    id: '/material/recruit',
    path: '/material/recruit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialProductRoute =
  AuthenticatedMaterialProductRouteImport.update({
    id: '/material/product',
    path: '/material/product',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialNoteRoute =
  AuthenticatedMaterialNoteRouteImport.update({
    id: '/material/note',
    path: '/material/note',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialNewsRoute =
  AuthenticatedMaterialNewsRouteImport.update({
    id: '/material/news',
    path: '/material/news',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialImageRoute =
  AuthenticatedMaterialImageRouteImport.update({
    id: '/material/image',
    path: '/material/image',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialFileRoute =
  AuthenticatedMaterialFileRouteImport.update({
    id: '/material/file',
    path: '/material/file',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialCustomizeRoute =
  AuthenticatedMaterialCustomizeRouteImport.update({
    id: '/material/customize',
    path: '/material/customize',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialCompanyRoute =
  AuthenticatedMaterialCompanyRouteImport.update({
    id: '/material/company',
    path: '/material/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialBookRoute =
  AuthenticatedMaterialBookRouteImport.update({
    id: '/material/book',
    path: '/material/book',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialBidRoute =
  AuthenticatedMaterialBidRouteImport.update({
    id: '/material/bid',
    path: '/material/bid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialAudioRoute =
  AuthenticatedMaterialAudioRouteImport.update({
    id: '/material/audio',
    path: '/material/audio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialArticleRoute =
  AuthenticatedMaterialArticleRouteImport.update({
    id: '/material/article',
    path: '/material/article',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialAccountRoute =
  AuthenticatedMaterialAccountRouteImport.update({
    id: '/material/account',
    path: '/material/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/user-management': typeof AuthenticatedUserManagementRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/material/account': typeof AuthenticatedMaterialAccountRoute
  '/material/article': typeof AuthenticatedMaterialArticleRoute
  '/material/audio': typeof AuthenticatedMaterialAudioRoute
  '/material/bid': typeof AuthenticatedMaterialBidRoute
  '/material/book': typeof AuthenticatedMaterialBookRoute
  '/material/company': typeof AuthenticatedMaterialCompanyRoute
  '/material/customize': typeof AuthenticatedMaterialCustomizeRoute
  '/material/file': typeof AuthenticatedMaterialFileRoute
  '/material/image': typeof AuthenticatedMaterialImageRoute
  '/material/news': typeof AuthenticatedMaterialNewsRoute
  '/material/note': typeof AuthenticatedMaterialNoteRoute
  '/material/product': typeof AuthenticatedMaterialProductRoute
  '/material/recruit': typeof AuthenticatedMaterialRecruitRoute
  '/material/shop': typeof AuthenticatedMaterialShopRoute
  '/material/speech': typeof AuthenticatedMaterialSpeechRoute
  '/material/subs': typeof AuthenticatedMaterialSubsRoute
  '/material/trade': typeof AuthenticatedMaterialTradeRoute
  '/material/unknown': typeof AuthenticatedMaterialUnknownRoute
  '/material/video': typeof AuthenticatedMaterialVideoRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/actors': typeof AuthenticatedActorsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/articles': typeof AuthenticatedArticlesIndexRoute
  '/blackwords': typeof AuthenticatedBlackwordsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/clusters': typeof AuthenticatedClustersIndexRoute
  '/entrypoints': typeof AuthenticatedEntrypointsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/industries': typeof AuthenticatedIndustriesIndexRoute
  '/jobgroups': typeof AuthenticatedJobgroupsIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/links': typeof AuthenticatedLinksIndexRoute
  '/pre-tasks': typeof AuthenticatedPreTasksIndexRoute
  '/prejobs': typeof AuthenticatedPrejobsIndexRoute
  '/reqs': typeof AuthenticatedReqsIndexRoute
  '/servers': typeof AuthenticatedServersIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/spider-packages': typeof AuthenticatedSpiderPackagesIndexRoute
  '/spider-sessions': typeof AuthenticatedSpiderSessionsIndexRoute
  '/spiders': typeof AuthenticatedSpidersIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/websites': typeof AuthenticatedWebsitesIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/user-management': typeof AuthenticatedUserManagementRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/material/account': typeof AuthenticatedMaterialAccountRoute
  '/material/article': typeof AuthenticatedMaterialArticleRoute
  '/material/audio': typeof AuthenticatedMaterialAudioRoute
  '/material/bid': typeof AuthenticatedMaterialBidRoute
  '/material/book': typeof AuthenticatedMaterialBookRoute
  '/material/company': typeof AuthenticatedMaterialCompanyRoute
  '/material/customize': typeof AuthenticatedMaterialCustomizeRoute
  '/material/file': typeof AuthenticatedMaterialFileRoute
  '/material/image': typeof AuthenticatedMaterialImageRoute
  '/material/news': typeof AuthenticatedMaterialNewsRoute
  '/material/note': typeof AuthenticatedMaterialNoteRoute
  '/material/product': typeof AuthenticatedMaterialProductRoute
  '/material/recruit': typeof AuthenticatedMaterialRecruitRoute
  '/material/shop': typeof AuthenticatedMaterialShopRoute
  '/material/speech': typeof AuthenticatedMaterialSpeechRoute
  '/material/subs': typeof AuthenticatedMaterialSubsRoute
  '/material/trade': typeof AuthenticatedMaterialTradeRoute
  '/material/unknown': typeof AuthenticatedMaterialUnknownRoute
  '/material/video': typeof AuthenticatedMaterialVideoRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/actors': typeof AuthenticatedActorsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/articles': typeof AuthenticatedArticlesIndexRoute
  '/blackwords': typeof AuthenticatedBlackwordsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/clusters': typeof AuthenticatedClustersIndexRoute
  '/entrypoints': typeof AuthenticatedEntrypointsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/industries': typeof AuthenticatedIndustriesIndexRoute
  '/jobgroups': typeof AuthenticatedJobgroupsIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/links': typeof AuthenticatedLinksIndexRoute
  '/pre-tasks': typeof AuthenticatedPreTasksIndexRoute
  '/prejobs': typeof AuthenticatedPrejobsIndexRoute
  '/reqs': typeof AuthenticatedReqsIndexRoute
  '/servers': typeof AuthenticatedServersIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/spider-packages': typeof AuthenticatedSpiderPackagesIndexRoute
  '/spider-sessions': typeof AuthenticatedSpiderSessionsIndexRoute
  '/spiders': typeof AuthenticatedSpidersIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/websites': typeof AuthenticatedWebsitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/user-management': typeof AuthenticatedUserManagementRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/material/account': typeof AuthenticatedMaterialAccountRoute
  '/_authenticated/material/article': typeof AuthenticatedMaterialArticleRoute
  '/_authenticated/material/audio': typeof AuthenticatedMaterialAudioRoute
  '/_authenticated/material/bid': typeof AuthenticatedMaterialBidRoute
  '/_authenticated/material/book': typeof AuthenticatedMaterialBookRoute
  '/_authenticated/material/company': typeof AuthenticatedMaterialCompanyRoute
  '/_authenticated/material/customize': typeof AuthenticatedMaterialCustomizeRoute
  '/_authenticated/material/file': typeof AuthenticatedMaterialFileRoute
  '/_authenticated/material/image': typeof AuthenticatedMaterialImageRoute
  '/_authenticated/material/news': typeof AuthenticatedMaterialNewsRoute
  '/_authenticated/material/note': typeof AuthenticatedMaterialNoteRoute
  '/_authenticated/material/product': typeof AuthenticatedMaterialProductRoute
  '/_authenticated/material/recruit': typeof AuthenticatedMaterialRecruitRoute
  '/_authenticated/material/shop': typeof AuthenticatedMaterialShopRoute
  '/_authenticated/material/speech': typeof AuthenticatedMaterialSpeechRoute
  '/_authenticated/material/subs': typeof AuthenticatedMaterialSubsRoute
  '/_authenticated/material/trade': typeof AuthenticatedMaterialTradeRoute
  '/_authenticated/material/unknown': typeof AuthenticatedMaterialUnknownRoute
  '/_authenticated/material/video': typeof AuthenticatedMaterialVideoRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/actors/': typeof AuthenticatedActorsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/articles/': typeof AuthenticatedArticlesIndexRoute
  '/_authenticated/blackwords/': typeof AuthenticatedBlackwordsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/clusters/': typeof AuthenticatedClustersIndexRoute
  '/_authenticated/entrypoints/': typeof AuthenticatedEntrypointsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/industries/': typeof AuthenticatedIndustriesIndexRoute
  '/_authenticated/jobgroups/': typeof AuthenticatedJobgroupsIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/links/': typeof AuthenticatedLinksIndexRoute
  '/_authenticated/pre-tasks/': typeof AuthenticatedPreTasksIndexRoute
  '/_authenticated/prejobs/': typeof AuthenticatedPrejobsIndexRoute
  '/_authenticated/reqs/': typeof AuthenticatedReqsIndexRoute
  '/_authenticated/servers/': typeof AuthenticatedServersIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/spider-packages/': typeof AuthenticatedSpiderPackagesIndexRoute
  '/_authenticated/spider-sessions/': typeof AuthenticatedSpiderSessionsIndexRoute
  '/_authenticated/spiders/': typeof AuthenticatedSpidersIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/websites/': typeof AuthenticatedWebsitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/user-management'
    | '/'
    | '/errors/$error'
    | '/material/account'
    | '/material/article'
    | '/material/audio'
    | '/material/bid'
    | '/material/book'
    | '/material/company'
    | '/material/customize'
    | '/material/file'
    | '/material/image'
    | '/material/news'
    | '/material/note'
    | '/material/product'
    | '/material/recruit'
    | '/material/shop'
    | '/material/speech'
    | '/material/subs'
    | '/material/trade'
    | '/material/unknown'
    | '/material/video'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/actors'
    | '/apps'
    | '/articles'
    | '/blackwords'
    | '/chats'
    | '/clusters'
    | '/entrypoints'
    | '/help-center'
    | '/industries'
    | '/jobgroups'
    | '/jobs'
    | '/links'
    | '/pre-tasks'
    | '/prejobs'
    | '/reqs'
    | '/servers'
    | '/services'
    | '/settings/'
    | '/spider-packages'
    | '/spider-sessions'
    | '/spiders'
    | '/tasks'
    | '/templates'
    | '/users'
    | '/websites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/user-management'
    | '/'
    | '/errors/$error'
    | '/material/account'
    | '/material/article'
    | '/material/audio'
    | '/material/bid'
    | '/material/book'
    | '/material/company'
    | '/material/customize'
    | '/material/file'
    | '/material/image'
    | '/material/news'
    | '/material/note'
    | '/material/product'
    | '/material/recruit'
    | '/material/shop'
    | '/material/speech'
    | '/material/subs'
    | '/material/trade'
    | '/material/unknown'
    | '/material/video'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/actors'
    | '/apps'
    | '/articles'
    | '/blackwords'
    | '/chats'
    | '/clusters'
    | '/entrypoints'
    | '/help-center'
    | '/industries'
    | '/jobgroups'
    | '/jobs'
    | '/links'
    | '/pre-tasks'
    | '/prejobs'
    | '/reqs'
    | '/servers'
    | '/services'
    | '/settings'
    | '/spider-packages'
    | '/spider-sessions'
    | '/spiders'
    | '/tasks'
    | '/templates'
    | '/users'
    | '/websites'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/user-management'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/material/account'
    | '/_authenticated/material/article'
    | '/_authenticated/material/audio'
    | '/_authenticated/material/bid'
    | '/_authenticated/material/book'
    | '/_authenticated/material/company'
    | '/_authenticated/material/customize'
    | '/_authenticated/material/file'
    | '/_authenticated/material/image'
    | '/_authenticated/material/news'
    | '/_authenticated/material/note'
    | '/_authenticated/material/product'
    | '/_authenticated/material/recruit'
    | '/_authenticated/material/shop'
    | '/_authenticated/material/speech'
    | '/_authenticated/material/subs'
    | '/_authenticated/material/trade'
    | '/_authenticated/material/unknown'
    | '/_authenticated/material/video'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/actors/'
    | '/_authenticated/apps/'
    | '/_authenticated/articles/'
    | '/_authenticated/blackwords/'
    | '/_authenticated/chats/'
    | '/_authenticated/clusters/'
    | '/_authenticated/entrypoints/'
    | '/_authenticated/help-center/'
    | '/_authenticated/industries/'
    | '/_authenticated/jobgroups/'
    | '/_authenticated/jobs/'
    | '/_authenticated/links/'
    | '/_authenticated/pre-tasks/'
    | '/_authenticated/prejobs/'
    | '/_authenticated/reqs/'
    | '/_authenticated/servers/'
    | '/_authenticated/services/'
    | '/_authenticated/settings/'
    | '/_authenticated/spider-packages/'
    | '/_authenticated/spider-sessions/'
    | '/_authenticated/spiders/'
    | '/_authenticated/tasks/'
    | '/_authenticated/templates/'
    | '/_authenticated/users/'
    | '/_authenticated/websites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-management': {
      id: '/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AuthenticatedUserManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/websites/': {
      id: '/_authenticated/websites/'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof AuthenticatedWebsitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spiders/': {
      id: '/_authenticated/spiders/'
      path: '/spiders'
      fullPath: '/spiders'
      preLoaderRoute: typeof AuthenticatedSpidersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spider-sessions/': {
      id: '/_authenticated/spider-sessions/'
      path: '/spider-sessions'
      fullPath: '/spider-sessions'
      preLoaderRoute: typeof AuthenticatedSpiderSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spider-packages/': {
      id: '/_authenticated/spider-packages/'
      path: '/spider-packages'
      fullPath: '/spider-packages'
      preLoaderRoute: typeof AuthenticatedSpiderPackagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servers/': {
      id: '/_authenticated/servers/'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AuthenticatedServersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reqs/': {
      id: '/_authenticated/reqs/'
      path: '/reqs'
      fullPath: '/reqs'
      preLoaderRoute: typeof AuthenticatedReqsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prejobs/': {
      id: '/_authenticated/prejobs/'
      path: '/prejobs'
      fullPath: '/prejobs'
      preLoaderRoute: typeof AuthenticatedPrejobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pre-tasks/': {
      id: '/_authenticated/pre-tasks/'
      path: '/pre-tasks'
      fullPath: '/pre-tasks'
      preLoaderRoute: typeof AuthenticatedPreTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links/': {
      id: '/_authenticated/links/'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobgroups/': {
      id: '/_authenticated/jobgroups/'
      path: '/jobgroups'
      fullPath: '/jobgroups'
      preLoaderRoute: typeof AuthenticatedJobgroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industries/': {
      id: '/_authenticated/industries/'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof AuthenticatedIndustriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrypoints/': {
      id: '/_authenticated/entrypoints/'
      path: '/entrypoints'
      fullPath: '/entrypoints'
      preLoaderRoute: typeof AuthenticatedEntrypointsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clusters/': {
      id: '/_authenticated/clusters/'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof AuthenticatedClustersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blackwords/': {
      id: '/_authenticated/blackwords/'
      path: '/blackwords'
      fullPath: '/blackwords'
      preLoaderRoute: typeof AuthenticatedBlackwordsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articles/': {
      id: '/_authenticated/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AuthenticatedArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actors/': {
      id: '/_authenticated/actors/'
      path: '/actors'
      fullPath: '/actors'
      preLoaderRoute: typeof AuthenticatedActorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/material/video': {
      id: '/_authenticated/material/video'
      path: '/material/video'
      fullPath: '/material/video'
      preLoaderRoute: typeof AuthenticatedMaterialVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/unknown': {
      id: '/_authenticated/material/unknown'
      path: '/material/unknown'
      fullPath: '/material/unknown'
      preLoaderRoute: typeof AuthenticatedMaterialUnknownRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/trade': {
      id: '/_authenticated/material/trade'
      path: '/material/trade'
      fullPath: '/material/trade'
      preLoaderRoute: typeof AuthenticatedMaterialTradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/subs': {
      id: '/_authenticated/material/subs'
      path: '/material/subs'
      fullPath: '/material/subs'
      preLoaderRoute: typeof AuthenticatedMaterialSubsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/speech': {
      id: '/_authenticated/material/speech'
      path: '/material/speech'
      fullPath: '/material/speech'
      preLoaderRoute: typeof AuthenticatedMaterialSpeechRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/shop': {
      id: '/_authenticated/material/shop'
      path: '/material/shop'
      fullPath: '/material/shop'
      preLoaderRoute: typeof AuthenticatedMaterialShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/recruit': {
      id: '/_authenticated/material/recruit'
      path: '/material/recruit'
      fullPath: '/material/recruit'
      preLoaderRoute: typeof AuthenticatedMaterialRecruitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/product': {
      id: '/_authenticated/material/product'
      path: '/material/product'
      fullPath: '/material/product'
      preLoaderRoute: typeof AuthenticatedMaterialProductRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/note': {
      id: '/_authenticated/material/note'
      path: '/material/note'
      fullPath: '/material/note'
      preLoaderRoute: typeof AuthenticatedMaterialNoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/news': {
      id: '/_authenticated/material/news'
      path: '/material/news'
      fullPath: '/material/news'
      preLoaderRoute: typeof AuthenticatedMaterialNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/image': {
      id: '/_authenticated/material/image'
      path: '/material/image'
      fullPath: '/material/image'
      preLoaderRoute: typeof AuthenticatedMaterialImageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/file': {
      id: '/_authenticated/material/file'
      path: '/material/file'
      fullPath: '/material/file'
      preLoaderRoute: typeof AuthenticatedMaterialFileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/customize': {
      id: '/_authenticated/material/customize'
      path: '/material/customize'
      fullPath: '/material/customize'
      preLoaderRoute: typeof AuthenticatedMaterialCustomizeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/company': {
      id: '/_authenticated/material/company'
      path: '/material/company'
      fullPath: '/material/company'
      preLoaderRoute: typeof AuthenticatedMaterialCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/book': {
      id: '/_authenticated/material/book'
      path: '/material/book'
      fullPath: '/material/book'
      preLoaderRoute: typeof AuthenticatedMaterialBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/bid': {
      id: '/_authenticated/material/bid'
      path: '/material/bid'
      fullPath: '/material/bid'
      preLoaderRoute: typeof AuthenticatedMaterialBidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/audio': {
      id: '/_authenticated/material/audio'
      path: '/material/audio'
      fullPath: '/material/audio'
      preLoaderRoute: typeof AuthenticatedMaterialAudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/article': {
      id: '/_authenticated/material/article'
      path: '/material/article'
      fullPath: '/material/article'
      preLoaderRoute: typeof AuthenticatedMaterialArticleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/account': {
      id: '/_authenticated/material/account'
      path: '/material/account'
      fullPath: '/material/account'
      preLoaderRoute: typeof AuthenticatedMaterialAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedUserManagementRoute: typeof AuthenticatedUserManagementRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedMaterialAccountRoute: typeof AuthenticatedMaterialAccountRoute
  AuthenticatedMaterialArticleRoute: typeof AuthenticatedMaterialArticleRoute
  AuthenticatedMaterialAudioRoute: typeof AuthenticatedMaterialAudioRoute
  AuthenticatedMaterialBidRoute: typeof AuthenticatedMaterialBidRoute
  AuthenticatedMaterialBookRoute: typeof AuthenticatedMaterialBookRoute
  AuthenticatedMaterialCompanyRoute: typeof AuthenticatedMaterialCompanyRoute
  AuthenticatedMaterialCustomizeRoute: typeof AuthenticatedMaterialCustomizeRoute
  AuthenticatedMaterialFileRoute: typeof AuthenticatedMaterialFileRoute
  AuthenticatedMaterialImageRoute: typeof AuthenticatedMaterialImageRoute
  AuthenticatedMaterialNewsRoute: typeof AuthenticatedMaterialNewsRoute
  AuthenticatedMaterialNoteRoute: typeof AuthenticatedMaterialNoteRoute
  AuthenticatedMaterialProductRoute: typeof AuthenticatedMaterialProductRoute
  AuthenticatedMaterialRecruitRoute: typeof AuthenticatedMaterialRecruitRoute
  AuthenticatedMaterialShopRoute: typeof AuthenticatedMaterialShopRoute
  AuthenticatedMaterialSpeechRoute: typeof AuthenticatedMaterialSpeechRoute
  AuthenticatedMaterialSubsRoute: typeof AuthenticatedMaterialSubsRoute
  AuthenticatedMaterialTradeRoute: typeof AuthenticatedMaterialTradeRoute
  AuthenticatedMaterialUnknownRoute: typeof AuthenticatedMaterialUnknownRoute
  AuthenticatedMaterialVideoRoute: typeof AuthenticatedMaterialVideoRoute
  AuthenticatedActorsIndexRoute: typeof AuthenticatedActorsIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedArticlesIndexRoute: typeof AuthenticatedArticlesIndexRoute
  AuthenticatedBlackwordsIndexRoute: typeof AuthenticatedBlackwordsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedClustersIndexRoute: typeof AuthenticatedClustersIndexRoute
  AuthenticatedEntrypointsIndexRoute: typeof AuthenticatedEntrypointsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedIndustriesIndexRoute: typeof AuthenticatedIndustriesIndexRoute
  AuthenticatedJobgroupsIndexRoute: typeof AuthenticatedJobgroupsIndexRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedLinksIndexRoute: typeof AuthenticatedLinksIndexRoute
  AuthenticatedPreTasksIndexRoute: typeof AuthenticatedPreTasksIndexRoute
  AuthenticatedPrejobsIndexRoute: typeof AuthenticatedPrejobsIndexRoute
  AuthenticatedReqsIndexRoute: typeof AuthenticatedReqsIndexRoute
  AuthenticatedServersIndexRoute: typeof AuthenticatedServersIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
  AuthenticatedSpiderPackagesIndexRoute: typeof AuthenticatedSpiderPackagesIndexRoute
  AuthenticatedSpiderSessionsIndexRoute: typeof AuthenticatedSpiderSessionsIndexRoute
  AuthenticatedSpidersIndexRoute: typeof AuthenticatedSpidersIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWebsitesIndexRoute: typeof AuthenticatedWebsitesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedUserManagementRoute: AuthenticatedUserManagementRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedMaterialAccountRoute: AuthenticatedMaterialAccountRoute,
  AuthenticatedMaterialArticleRoute: AuthenticatedMaterialArticleRoute,
  AuthenticatedMaterialAudioRoute: AuthenticatedMaterialAudioRoute,
  AuthenticatedMaterialBidRoute: AuthenticatedMaterialBidRoute,
  AuthenticatedMaterialBookRoute: AuthenticatedMaterialBookRoute,
  AuthenticatedMaterialCompanyRoute: AuthenticatedMaterialCompanyRoute,
  AuthenticatedMaterialCustomizeRoute: AuthenticatedMaterialCustomizeRoute,
  AuthenticatedMaterialFileRoute: AuthenticatedMaterialFileRoute,
  AuthenticatedMaterialImageRoute: AuthenticatedMaterialImageRoute,
  AuthenticatedMaterialNewsRoute: AuthenticatedMaterialNewsRoute,
  AuthenticatedMaterialNoteRoute: AuthenticatedMaterialNoteRoute,
  AuthenticatedMaterialProductRoute: AuthenticatedMaterialProductRoute,
  AuthenticatedMaterialRecruitRoute: AuthenticatedMaterialRecruitRoute,
  AuthenticatedMaterialShopRoute: AuthenticatedMaterialShopRoute,
  AuthenticatedMaterialSpeechRoute: AuthenticatedMaterialSpeechRoute,
  AuthenticatedMaterialSubsRoute: AuthenticatedMaterialSubsRoute,
  AuthenticatedMaterialTradeRoute: AuthenticatedMaterialTradeRoute,
  AuthenticatedMaterialUnknownRoute: AuthenticatedMaterialUnknownRoute,
  AuthenticatedMaterialVideoRoute: AuthenticatedMaterialVideoRoute,
  AuthenticatedActorsIndexRoute: AuthenticatedActorsIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedArticlesIndexRoute: AuthenticatedArticlesIndexRoute,
  AuthenticatedBlackwordsIndexRoute: AuthenticatedBlackwordsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedClustersIndexRoute: AuthenticatedClustersIndexRoute,
  AuthenticatedEntrypointsIndexRoute: AuthenticatedEntrypointsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedIndustriesIndexRoute: AuthenticatedIndustriesIndexRoute,
  AuthenticatedJobgroupsIndexRoute: AuthenticatedJobgroupsIndexRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedLinksIndexRoute: AuthenticatedLinksIndexRoute,
  AuthenticatedPreTasksIndexRoute: AuthenticatedPreTasksIndexRoute,
  AuthenticatedPrejobsIndexRoute: AuthenticatedPrejobsIndexRoute,
  AuthenticatedReqsIndexRoute: AuthenticatedReqsIndexRoute,
  AuthenticatedServersIndexRoute: AuthenticatedServersIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
  AuthenticatedSpiderPackagesIndexRoute: AuthenticatedSpiderPackagesIndexRoute,
  AuthenticatedSpiderSessionsIndexRoute: AuthenticatedSpiderSessionsIndexRoute,
  AuthenticatedSpidersIndexRoute: AuthenticatedSpidersIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWebsitesIndexRoute: AuthenticatedWebsitesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
